version: '3.3'
services:
  react-dev:
    container_name: cb-one
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
