version: '3.3'
services:
  react-dev:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
