version: '3.3'
services:
  react-dev:
    container_name: rb-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
